networks:
  todo-app-network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - todo-app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000/api
      - WDS_SOCKET_PORT=0
    command: npm start
    depends_on:
      - server
    networks:
      - todo-app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: todo-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - MONGODB_URI=mongodb://mongodb:27017/todos
      - EMAIL_USER=bogdanmihailov12@gmail.com
      - EMAIL_PASS=qrjt ykjj ceqc xuyo
      - POP3_HOST=pop.gmail.com
      - POP3_PORT=995
      - POP3_TLS=true
    command: npm run dev
    depends_on:
      - mongodb
    networks:
      - todo-app-network

volumes:
  mongodb-data: 